### ISSUE TITLE
[pyCoin] HTTPS Error!

### ISSUE THREAD

**Issue by hsyndeniz** [avnigenc/pyCoin#5]
#### Expected behavior
When you go to PyCoin, you will see 2 tabs in the box! Check wallet and Create Wallet tabs.  You can login to your wallet in check wallet tab. If you do not have a pyCoin wallet, you can create a new wallet with the "Create a Wallet" tab.

#### Actual behavior
The "Create a Wallet" tab does not work when you go to pyCoin's home page via HTTPS. It only works with HTTP.

#### How to reproduce
-  Go to pyCoin homepage! 
>https://py-coin.herokuapp.com
- Try clicking on the Create a Wallet tab.  
<hr>
*   Browser:      Tested with Opera and Google Chrome!

*   Operating system:      Mac OS Sierra

<hr>

#### Recording Of The Bug
![](https://media.giphy.com/media/xUOwGhqt0co79i7Lfq/giphy.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@hsynterkr/pycoin-https-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by avnigenc** [comment]
Thank you, fixed. @codingdefined
